version: "3.3"
services:
  web:
    build: .
    volumes:
      - .:/product_api
    image: product_api:latest
    command: bundle exec rails s -u puma -p 3000 -b '0.0.0.0'
    env_file:
      - '.env.dev'
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true  
  db:
    image: postgres:14.1
    ports:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust