default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: project_api_dev
  username: postgres
  password:
  host: db
  port: 5432

test:
  <<: *default
  database: project_api_test
  username: postgres
  password:
  host: db
  port: 5432
